/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //researchSidebar: [{type: 'autogenerated', dirName: './docs/research'}],
  //blogSidebar: [{type: 'autogenerated', dirName: './blog'}],

  // But you can create a sidebar manually
  
  ResearchSidebar: {
    "Cozie": [
      "cozie/intro_cozie", 
      "cozie/cozie_apple_vs_fitbit",
      "cozie/cozie_watches"
    ],

    "Publications": [
      "research/publications_cozie",
      "research/publications_cozie_reviews",
      //"research/publications_EMA",
      //"research/publications_JITAI"
      ],
  }

};

module.exports = sidebars;

